name: TuxTechCli Pull Request Checks Github Action

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '*'  # All branches
      - '!master'  # Except master

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check PR Title
        run: |
          if [[ ! ${{ github.event.pull_request.title }} =~ ^\[.*\].* ]]; then
            echo "::error::PR title must start with a type in square brackets (e.g., [feat], [fix], [docs])"
            exit 1
          fi
      - name: Run Shell Linting
        uses: koalaman/shellcheck@v0.9.0
        with:
          files: ./**/*.sh
      - name: Check Python Files
        run: |
          python -m pip install pylint
          pylint *.py
